/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : string,
  'createdAt' : Time,
  'deliveryTime' : string,
  'paymentProof' : [] | [PaymentProof],
  'customerAddress' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type OrderStatus = { 'verified' : null } |
  { 'pending' : null };
export interface PaymentProof {
  'proofText' : [] | [string],
  'screenshotUrl' : [] | [string],
}
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface Product {
  'offer' : [] | [string],
  'name' : string,
  'price' : number,
}
export interface ShopData {
  'ownerName' : string,
  'payments' : Array<ShopPaymentInfo>,
  'businessName' : string,
  'address' : string,
  'phone' : string,
}
export interface ShopLocation { 'latitude' : number, 'longitude' : number }
export interface ShopPaymentInfo {
  'network' : string,
  'phoneNumber' : string,
  'accountHolder' : string,
}
export interface ShopSocials {
  'tiktok' : string,
  'instagram' : string,
  'photoUrl' : string,
  'facebook' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMyShop' : ActorMethod<[], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllShops' : ActorMethod<[], Array<[Principal, ShopData]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[string], Array<Order>>,
  'getOrdersForShop' : ActorMethod<[], Array<Order>>,
  'getProductsForShop' : ActorMethod<[Principal], Array<Product>>,
  'getShopLocation' : ActorMethod<[Principal], [] | [ShopLocation]>,
  'getShopSocials' : ActorMethod<[Principal], [] | [ShopSocials]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Principal, Order], undefined>,
  'registerShop' : ActorMethod<[ShopData], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setShopLocation' : ActorMethod<[number, number], undefined>,
  'submitPaymentProof' : ActorMethod<
    [Principal, bigint, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateShop' : ActorMethod<[ShopData], undefined>,
  'updateShopSocials' : ActorMethod<[ShopSocials], undefined>,
  'verifyOrder' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];