/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'createdAt' : Time,
  'deliveryTime' : string,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type OrderStatus = { 'verified' : null } |
  { 'pending' : null };
export interface Product { 'name' : string, 'price' : number }
export interface ShopData {
  'ownerName' : string,
  'businessName' : string,
  'address' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllShops' : ActorMethod<[], Array<[Principal, ShopData]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrdersForShop' : ActorMethod<[], Array<Order>>,
  'getProductsForShop' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Principal, Order], undefined>,
  'registerShop' : ActorMethod<[ShopData], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateShop' : ActorMethod<[ShopData], undefined>,
  'verifyOrder' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];