/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Float64 });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShopData = IDL.Record({
  'ownerName' : IDL.Text,
  'businessName' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'deliveryTime' : IDL.Text,
  'customerAddress' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Float64,
});
export const ShopLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ShopSocials = IDL.Record({
  'tiktok' : IDL.Text,
  'instagram' : IDL.Text,
  'photoUrl' : IDL.Text,
  'facebook' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllShops' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ShopData))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrdersForShop' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductsForShop' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getShopLocation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ShopLocation)],
      ['query'],
    ),
  'getShopSocials' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ShopSocials)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Principal, Order], [], []),
  'registerShop' : IDL.Func([ShopData], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setShopLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateShop' : IDL.Func([ShopData], [], []),
  'updateShopSocials' : IDL.Func([ShopSocials], [], []),
  'verifyOrder' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Float64 });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShopData = IDL.Record({
    'ownerName' : IDL.Text,
    'businessName' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'deliveryTime' : IDL.Text,
    'customerAddress' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Float64,
  });
  const ShopLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ShopSocials = IDL.Record({
    'tiktok' : IDL.Text,
    'instagram' : IDL.Text,
    'photoUrl' : IDL.Text,
    'facebook' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllShops' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ShopData))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrdersForShop' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductsForShop' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getShopLocation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ShopLocation)],
        ['query'],
      ),
    'getShopSocials' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ShopSocials)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Principal, Order], [], []),
    'registerShop' : IDL.Func([ShopData], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setShopLocation' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateShop' : IDL.Func([ShopData], [], []),
    'updateShopSocials' : IDL.Func([ShopSocials], [], []),
    'verifyOrder' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };